# Generated by Django 4.2.29 on 2026-03-19 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('activity_created', 'Activity Created'), ('pipeline_moved', 'Pipeline Stage Changed'), ('system', 'System Notification')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_lead_id', models.UUIDField(blank=True, null=True)),
                ('related_activity_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
