# Generated by Django 4.2.29 on 2026-03-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetransitionlog',
            name='transitioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinelead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='pipelinelead',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_entries', to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinelead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_in_stage', to='pipelines.pipelinestage'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('pipeline', 'name'), ('pipeline', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinelead',
            unique_together={('lead', 'pipeline')},
        ),
    ]
